### PR TITLE
Phone #58 [TGER-111]

### PR DESCRIPTION
**Pull request by devjk1**
#58 

- add Migration / Model for Phone

_Note:_
There is a format called E.164, varchar(15)
https://www.twilio.com/docs/glossary/what-e164
For _Validation_ and _Formatting_, we can use Twilio if we use E.164
https://www.twilio.com/docs/lookup

### CODE REVIEW

**Comment by drewroberts** [comment]
I need to think about this model a little more and decide what all it needs. I'm still in the brainstorming phase on it.

**Comment by devjk1** [comment]
- added Models PhoneArea, CountryCallingcode
- updated Model relationships

_Note:_
Model CountryCallingcode
`$table->foreignIdFor(app('country')); // Some countries have more than one Calling Code`
Instead of Country hasMany CountryCallingcode, I used CountryCallingcode hasMany Country, e.g. +1 for USA, Canada

**Comment by drewroberts** [comment]
I am adding these classes to the support config here:

- https://github.com/tipoff/support/pull/99

**Comment by drewroberts** [comment]
@devjk1 It's the other way around from your comment:

> Note:
> Model CountryCallingcode
> $table->foreignIdFor(app('country')); // Some countries have more than one Calling Code
> Instead of Country hasMany CountryCallingcode, I used CountryCallingcode hasMany Country, e.g. +1 for USA, Canada

A country calling code can only belong to 1 country, but some countries have multiple country calling codes. List here:

- https://en.wikipedia.org/wiki/List_of_country_calling_codes

Dominican Republic is an example.

**Review by drewroberts — APPROVED** [review]
Thank you! 📲

**Pull request merged**
