### PR TITLE
Add scaffolding for custom field within package

### PR DESCRIPTION
**Pull request by pdbreen**

### CODE REVIEW

**Comment by pdbreen** [comment]
@devjk1 - here's a PR with the basic scaffolding to include one or more custom fields within a package.  You should take over this PR and implement the field(s) as you want them.  Always remember to `npm run prod` prior to commit to make sure the latest production build of `dist/js/field.js` and `dist/js/field.css` are the versions being committed.

**Comment by drewroberts** [comment]
@chx2 Can you also watch the development of this? You'll need to do something similar in the other packages that need custom Nova fields.

**Comment by devjk1** [comment]
@pdbreen Thanks a bunch!

**Comment by drewroberts** [comment]
> You should take over this PR and implement the field(s) as you want them. Always remember to npm run prod prior to commit to make sure the latest production build of dist/js/field.js and dist/js/field.css are the versions being committed.

@devjk1 Are you able to work on this today?

@joshtorres @phuclh Could we get this pushed through by Sunday evening? Thank you!

**Comment by joshtorres** [comment]
The whole team is working on this this weekend. 😃

**Pull request closed without merging**
