### PR TITLE
Domestic address javascript component autocomplete #72 #75 [TGER-140]

### PR DESCRIPTION
**Pull request by devjk1**
** do not TEST or merge, I need to add session tokens.

- Google Places API Key passed as a Laravel Mix env variable
- Need to create session tokens for billing puposes
- https://developers.google.com/maps/documentation/places/web-service/session-tokens

Need a test environment.

### CODE REVIEW

**Comment by drewroberts** [comment]
@kylebarney When you get a chance, could you make sure this is implementing the Google Places Autocomplete (https://github.com/tipoff/laravel-google-api/issues/18) as you had in mind with the tipoff/laravel-google-api package?

**Comment by devjk1** [comment]
https://developers.google.com/maps/documentation/places/web-service/autocomplete

In the example of the JSON response, the JSON object -> predictions -> terms, the address is split into terms/parts.  
If the parts are split consistently, then I can move on to extracting street address, city, state, etc...  then saving as a Model.
Unfortunately the example does not show a response where types=address, and we need a test environment to move further.

**Review by kylebarney — COMMENTED** [review]
@drewroberts To your question on this PR earlier this week, this code is using a client-side implementation rather than the server-side one that is included in the package that I pulled into `laravel-google-api`. If we wanted to go the server-side route, we would need to send a call to our own server and have that proxy through to the Places API like so: `(app()->make(\SKAgarwal\GoogleApi\PlacesApi::class))->placeAutocomplete('query-input');`

That being said, either approach will work. The client-side approach would make for a snappier experience, possibly at the expense of a little extra cost and less protection against abuse of the API key. The server-side could take a bit longer to respond since it is being proxied, but we could add rate-limiting if the number of requests/spamming is a concern.

**Comment by drewroberts** [comment]
Thank you, @kylebarney. Let's stick with this implementation then and we can refactor later if necessary to have rate-limiting functionality.

**Comment by devjk1** [comment]
Please delete/don't merge this PR.  I created a new PR to replace this.

**Pull request closed without merging**
